### ISSUE TITLE
Support for WSL sideloading

### ISSUE THREAD

**Issue by Ricky-N** [OfficeDev/office-toolbox#17]
I prefer to do most of my dev work / terminal interactions through WSL. This has worked out fairly well by mounting the c drive so that I can run visual applications like VS Code, but use an ubuntu terminal for things like actual `yarn build`. I would strongly prefer to not maintain a two dev environments (in and out of WSL).

I've tried using the sideload command in a plugin dev workflow, but the root path for the sideload directory is determined through `os.home()` which isn't quite the desired folder when operating through WSL, and can't be symlinked from my working directory: 
```Error: EXDEV: cross-device link not permitted, link '/mnt/c/Users/rniem/<dev path>/excel-plugin/my-office-add-in-manifest.xml' -> '/home/ricky/Library/Containers/com.microsoft.Excel/Data/Documents/wef/my-office-add-in-manifest.xml'```

Ideally this would be configurable so that WSL support can work with the mounted directory.

**Comment by akrantz** [comment]
I'm not sure how we would configure this.
