### ISSUE TITLE
Undefined files when searching manifest files

### ISSUE THREAD

**Issue by hongbo-miao** [OfficeDev/office-toolbox#2]
For https://github.com/Hongbo-Miao/office-addin-react

First `npm i`, then follow the steps below:

![image](https://user-images.githubusercontent.com/3375461/29438644-dfdc18f2-836c-11e7-95e1-338e22a8d86f.png)

You will reproduce the issue.

**Comment by gesiu** [comment]
Resolved in 8983b74
