### ISSUE TITLE
Manifest is not refreshed when sideloading

### ISSUE THREAD

**Issue by noon-otter** [OfficeDev/office-toolbox#24]
I cannot get my sideloaded TaskPane Excel add-in to reflect changes in the manifest.xml. I've changed all https locations to dummy strings that should fail, but when I sideload the add-in, Excel is pulling from the old manifest.xml somehow. 

Short of uninstalling and reinstalling Excel, I've tried everything I can think of. 

- Running sideload from a different location
- Doing a search of all files in my filesystem with the name "manifest.xml" and deleting those.
- Deleting every cached item from /User/AppData/Local/Microsoft/Office/16.0/Wef/
- Deleting everything from /User/AppData/Roaming/Microsoft/Windows/Recent Items

How can I update my manifest?

**Comment by akrantz** [comment]
The steps you've done should allow the manifest to be used.

Run "npm run validate" and make sure that the manifest is valid. Perhaps an error is prevent it from loading the updated manifest.

You could also try changing the id in the manifest. Easiest way is to use "npx office-addin-manifest modify --guid".

I hope that helps!

**Comment by akrantz** [comment]
Let us know whether you're still having an issue...

**Comment by noon-otter** [comment]
Thanks @akrantz! Changing the guid in the manifest was the only thing that solved the problem.
