### ISSUE TITLE
Error in sideloadManifest() not displayed to user

### ISSUE THREAD

**Issue by rob-deutsch** [OfficeDev/office-toolbox#25]
**Summary:** I am trying to sideload an manifest file named `manifest.xml` on macOS when my `/wef/` directory already has a `manifest.xml` from another addin. `office-toolbox` notices that they are two different files (because they have different dev/inodes) and refuses to sideload my manifest file.

**Expected behaviour:** `office-toolbox` should alert the user that the manifest file was _not_ sideloaded.

**Actual behaviour:** `office-toolbox` acts as if the manifest file was sideloaded.

**Relevant source code:**
https://github.com/OfficeDev/office-toolbox/blob/f3fbfad849c47ec2abccc70faaf87261ab83afa8/src/util.ts#L140-L147

**Suggested change:** I believe that the two manifest files are different if [stat.dev](https://nodejs.org/api/fs.html#fs_stats_dev) and [stat.ino](https://nodejs.org/api/fs.html#fs_stats_ino) are different. This lines checks BOTH are different. This should be changed.

**Comment by akrantz** [comment]
@TCourtneyOwen Did your recent changes happen to fix this?

**Comment by TCourtneyOwen** [comment]
@akrantz Yes, I believe my change should resolve the problem and obviate the need to even check for a duplicate manifest since we will now generate a unique manifest file name to put in the wef cache (e.g guid.manifest.xml)

**Comment by akrantz** [comment]
OK this should be fixed now.
