### ISSUE TITLE
remove command broken on mac

### ISSUE THREAD

**Issue by akrantz** [OfficeDev/office-toolbox#31]
I tried out office-toobox0.2.0 and "npx office-toolbox remove -a excel" will show the manifests, but if you pick one, it won't remove it.

**Comment by TCourtneyOwen** [comment]
I’ll look into this tomorrow

**Comment by TCourtneyOwen** [comment]
I am not seeing any problems with removing the manifest on Mac when stepping through the debugger.  I just tried doing an install of office-toolbox on my Mac machine and for some reason it's giving me version 0.1.1

**Comment by TCourtneyOwen** [comment]
As we discussed, the recent updates will remove manifests successfully if they contain a guid in the manifest name, but won't remove manifests that were sideloaded prior to the recent change that generates a unique manifest file name during sideload.  The problem looks to be with getSideloadManifestPath, which needs to be updated so it gets the path all manifest files, not just ones with the unique guid name

**Comment by akrantz** [comment]
It's broken if the manifest was added with an earlier version. Remove needs to use the path when the list is shown rather than composing it.

**Comment by akrantz** [comment]
@TCourtneyOwen Is this fixed now?

**Comment by akrantz** [comment]
Fixed with https://github.com/OfficeDev/office-toolbox/pull/33

**Comment by TCourtneyOwen** [comment]
Yes this is fixed
