### ISSUE TITLE
Can not sideload when Word is installed as app

### ISSUE THREAD

**Issue by rvanlaak** [OfficeDev/office-toolbox#37]
When Word is installed via the app store the sideload command throws the following exception:

![image](https://user-images.githubusercontent.com/2707563/62116775-0a1fde80-b2bb-11e9-8604-074c6c6a3480.png)

The path where Word gets installed as app is:

> C:\Program Files\WindowsApps\Microsoft.Office.Desktop.Word_16051.11901.20120.0_x86__8wekyb3d8bbwe\Office16

**Comment by SpacePotatoBear** [comment]
I am also getting this issue with Excel. 

The keys look like they're present in HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\16.0

maybe the app store just saves them to a different local?

**Comment by TCourtneyOwen** [comment]
@SpacePotatoBear Sorry to hear you are having problems with office-toolbox. We have recently moved the sideloading functionality in the [office-addin-debugging package](https://github.com/OfficeDev/Office-Addin-Scripts/tree/master/packages/office-addin-debugging).  I recommend adding this package to your project, running npm install and then adding a script like the following to your package.json:

"sideload": "office-addin-debugging start manifest.xml --app word",

Please let us know if that works for you.

Thanks,

Courtney

**Comment by akrantz** [comment]
@TCourtneyOwen I believe the issue here is that the desktop version of Office is installed from the Windows Store. My current understanding would be that the registry should work the same, but we should investigate whether the installation is different such that the registry entries being used for sideload are not available.

**Comment by akrantz** [comment]
Also, we should move this issue over to https://github.com/OfficeDev/Office-Addin-Scripts as the sideload functionality has been moved from office-toolbox over to office-addin-dev-settings (sideload, register, registered, and unregister commands).

**Comment by akrantz** [comment]
Issue moved to https://github.com/OfficeDev/Office-Addin-Scripts/issues/226.

**Comment by SpacePotatoBear** [comment]
@TCourtneyOwen it worked! Thanks a bunch.

**Comment by TCourtneyOwen** [comment]
Awesome glad to hear it!!
