### ISSUE TITLE
Validate fails if EquivalentAddins node appears before Hosts node in VersionOverrides

### ISSUE THREAD

**Issue by fds-ssg** [OfficeDev/office-toolbox#40]
Sample files
[manifest-sample-fail.xml.txt](https://github.com/OfficeDev/office-toolbox/files/4172621/manifest-sample-fail.xml.txt)
[manifest-sample-pass.xml.txt](https://github.com/OfficeDev/office-toolbox/files/4172622/manifest-sample-pass.xml.txt)

Using version 0.3.0, this node structure results in a failure:

```xml
<VersionOverrides ...>
  <EquivalentAddins>
  </EquivalentAddins>
  <Hosts>
  </Hosts>
  <Resources>
  </Resources>
</VersionOverrides>
```
Validate output:

> Validation: Failed
>
> Error #1: 
XML Schema Violation: Your manifest does not adhere to the current set of XML schema definitions for Office Add-in manifests. (link: https://aka.ms/add-in-manifest-schema-violation)
>  - Details: The element 'VersionOverrides' in namespace 'http://schemas.microsoft.com/office/taskpaneappversionoverrides' has invalid child element 'Hosts' in namespace 'http://schemas.microsoft.com/office/taskpaneappversionoverrides'. List of possible elements expected: 'ConnectedServiceControls' in namespace 'http://schemas.microsoft.com/office/taskpaneappversionoverrides' as well as any element in namespace 'http://schemas.microsoft.com/office/taskpaneappversionoverrides/1.1'.

Yet this succeeds:
```xml
<VersionOverrides ...>
  <Hosts>
  </Hosts>
  <Resources>
  </Resources>
  <EquivalentAddins>
  </EquivalentAddins>
</VersionOverrides>
```

If a certain ordering is required for VersionOverrides child elements, it would be helpful to specify that in the [VersionOverrides documentation](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/versionoverrides).

**Comment by akrantz** [comment]
See documentation: https://docs.microsoft.com/en-us/office/dev/add-ins/develop/manifest-element-ordering
