### ISSUE TITLE
Validation tool should detect RequestedHeight tag should come after label tag and before SourceLocation tag

### ISSUE THREAD

**Issue by exextoc** [OfficeDev/office-toolbox#42]
Github issue - https://github.com/OfficeDev/office-js/issues/1074

RequestedHeight tag should come after label tag and before SourceLocation tag must appear in the manifest validation tool

**Comment by akrantz** [comment]
office-toolbox is no longer used for validation. The office-addin-manifest "validate" command is used instead. Use `npx office-addin-manifest validate <manifest>` to do this validation.

This was just updated yesterday to use a different validation service. Please see whether this is still an issue. If it is, please raise the issue in the https://github.com/OfficeDev/Office-Addin-Scripts repository.
