### ISSUE TITLE
Should we ask user where to output the book to?  And/or output to temp directory?

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/office-toolbox#7]
Not sure I'm in love with dumping the file at the root; see the effect it had on source control, for example, for a file that I have no intention to check in.  And it's not necessarily a name I would have chosen.

![image](https://user-images.githubusercontent.com/2230453/30013399-2f70a392-90fb-11e7-9205-a79237fe3bfc.png)

I would recommend dumping to a temp directory instead.  If someone wants to keep the file, they can always "save as" it.

**Comment by akrantz** [comment]
We should put it in a temp directory with the filename based on the add-in guid from the manifest. That way it only has to be created if the file for that guid/version does not exist, otherwise it doesn't need to recreated it and can just open it.

**Comment by akrantz** [comment]
Fixed in https://github.com/OfficeDev/office-toolbox/pull/15.
