### ISSUE TITLE
Bower migration warning when installing office-toolbox

### ISSUE THREAD

**Issue by keyur32** [OfficeDev/office-toolbox#9]
Ran: npm install -g office-toolbox

c:\dev>npm install -g office-toolbox
npm WARN deprecated bower@1.8.2: ...psst! Your project can stop working at any moment because its dependencies can change. Prevent this by migrating to Yarn: https://bower.io/blog/2017/how-to-migrate-away-from-bower/

**Comment by akrantz** [comment]
Removed bower dependency in https://github.com/OfficeDev/office-toolbox/pull/14.

**Comment by akrantz** [comment]
Fixed. https://github.com/OfficeDev/office-toolbox/pull/14
